name: Build and Publish

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up C++ build environment
    - name: Install C++ dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake

    # Step 3: Set up .NET SDK
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' # Replace with your required version

    # Step 4: Verify versions
    - name: Verify installed versions
      run: |
        g++ --version
        dotnet --version

    # Step 5: Execute the script
    - name: Execute build and publish script
      run: |
        chmod +x ./build-shared-library-and-publish-dotnet-app.sh
        ./build-shared-library-and-publish-dotnet-app.sh

    # Step 6: Download the publish folder
    - name: Upload publish folder as artifact
      uses: actions/download-artifact@v4
      with:
        name: publish-folder
        path: publish/
